// <auto-generated />
using System;
using Kolokwium2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kolokwium2.Migrations
{
    [DbContext(typeof(Kolokwium2DbContext))]
    [Migration("20200619114946_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kolokwium2.Models.Artist", b =>
                {
                    b.Property<int>("IdArtist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdArtist");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            IdArtist = 1,
                            Nickname = "Zabor"
                        },
                        new
                        {
                            IdArtist = 2,
                            Nickname = "Adaś"
                        },
                        new
                        {
                            IdArtist = 3,
                            Nickname = "Krzychu"
                        },
                        new
                        {
                            IdArtist = 4,
                            Nickname = "Ela"
                        },
                        new
                        {
                            IdArtist = 5,
                            Nickname = "Eminem"
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.Artist_Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int>("IdArtist")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformanceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEvent", "IdArtist");

                    b.HasIndex("IdArtist");

                    b.ToTable("Artist_Event");

                    b.HasData(
                        new
                        {
                            IdEvent = 3,
                            IdArtist = 5,
                            PerformanceDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 4,
                            IdArtist = 5,
                            PerformanceDate = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 5,
                            IdArtist = 3,
                            PerformanceDate = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 5,
                            IdArtist = 2,
                            PerformanceDate = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 1,
                            IdArtist = 1,
                            PerformanceDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEvent");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            IdEvent = 1,
                            EndDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Połowinki",
                            StartDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 2,
                            EndDate = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Woodstock",
                            StartDate = new DateTime(2021, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 3,
                            EndDate = new DateTime(2019, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wixapol",
                            StartDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 4,
                            EndDate = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Skrra",
                            StartDate = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 5,
                            EndDate = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Impreza",
                            StartDate = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.Event_Organiser", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int>("IdOrganiser")
                        .HasColumnType("int");

                    b.HasKey("IdEvent", "IdOrganiser");

                    b.HasIndex("IdOrganiser");

                    b.ToTable("Event_Organiser");

                    b.HasData(
                        new
                        {
                            IdEvent = 1,
                            IdOrganiser = 2
                        },
                        new
                        {
                            IdEvent = 2,
                            IdOrganiser = 1
                        },
                        new
                        {
                            IdEvent = 3,
                            IdOrganiser = 5
                        },
                        new
                        {
                            IdEvent = 4,
                            IdOrganiser = 4
                        },
                        new
                        {
                            IdEvent = 1,
                            IdOrganiser = 3
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.Organiser", b =>
                {
                    b.Property<int>("IdOrganiser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdOrganiser");

                    b.ToTable("Organiser");

                    b.HasData(
                        new
                        {
                            IdOrganiser = 1,
                            Name = "MTV"
                        },
                        new
                        {
                            IdOrganiser = 2,
                            Name = "Szkoła"
                        },
                        new
                        {
                            IdOrganiser = 3,
                            Name = "TVP"
                        },
                        new
                        {
                            IdOrganiser = 4,
                            Name = "TVN"
                        },
                        new
                        {
                            IdOrganiser = 5,
                            Name = "Wixapol"
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.Artist_Event", b =>
                {
                    b.HasOne("Kolokwium2.Models.Artist", "IdArtistNavigation")
                        .WithMany("ArtistEvents")
                        .HasForeignKey("IdArtist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2.Models.Event", "IdEventNavigation")
                        .WithMany("ArtistEvents")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kolokwium2.Models.Event_Organiser", b =>
                {
                    b.HasOne("Kolokwium2.Models.Event", "IdEventNavigation")
                        .WithMany("EventOrganisers")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2.Models.Organiser", "IdOrganiserNavigation")
                        .WithMany("EventOrganisers")
                        .HasForeignKey("IdOrganiser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
